import type { LedgerEvent } from './types'

const metrics = (
  latencyMs: number,
  geminiCalls: number,
  escalated: boolean,
  inputTokens: number,
  outputTokens: number,
  thinkingTokens: number,
  cachedTokens: number,
) => ({
  latencyMs,
  geminiCalls,
  escalated,
  inputTokens,
  outputTokens,
  thinkingTokens,
  cachedTokens,
})

export const CLAIM = {
  id: 'C17',
  text: 'Compound X reduces tumor growth in vivo.',
  prior: 0.45,
} as const

export const DEMO_EVENTS: LedgerEvent[] = [
  {
    seq: 1,
    stepId: 'baseline-support',
    title: 'Verified study supports the claim',
    eventType: 'EVIDENCE_COMMITTED',
    verdict: 'COMMIT',
    integrity: 'L2 · VERIFIED',
    delta: 0.12,
    rootId: 'ROOT-SUPPORT-001',
    relation: 'supports',
    reversesSeqs: [],
    reasons: ['witness_spans_valid', 'provenance_verified', 'within_kl_budget'],
    tags: ['support', 'verified'],
    engine: {
      prior: 0.45,
      rawBf: 4,
      boundedDelta: 0.12,
      rootSpent: 0.12,
      posterior: 0.57,
      integrity: 'L2 · VERIFIED',
    },
    metrics: metrics(112, 2, false, 624, 148, 42, 198),
    explanation: 'External witnesses validated the claim mapping and spans. The update was clipped to the verified-evidence trust region.',
  },
  {
    seq: 2,
    stepId: 'credible-contradiction',
    title: 'Verified null result contradicts the claim',
    eventType: 'EVIDENCE_COMMITTED',
    verdict: 'COMMIT',
    integrity: 'L2 · VERIFIED',
    delta: -0.09,
    rootId: 'ROOT-NULL-001',
    relation: 'contradicts',
    reversesSeqs: [],
    reasons: ['witness_spans_valid', 'independent_root', 'within_kl_budget'],
    tags: ['contradiction', 'verified'],
    engine: {
      prior: 0.57,
      rawBf: 0.25,
      boundedDelta: -0.09,
      rootSpent: 0.09,
      posterior: 0.48,
      integrity: 'L2 · VERIFIED',
    },
    metrics: metrics(126, 2, false, 588, 139, 38, 176),
    explanation: 'A separately rooted null result contradicted C17. Its negative contribution stayed inside the L2 update bound.',
  },
  {
    seq: 3,
    stepId: 'schema-valid-semantic-attack',
    title: 'Semantic lie passes schema validation only',
    eventType: 'EVIDENCE_PROVISIONAL',
    verdict: 'PROVISIONAL',
    integrity: 'L1 · PARSED',
    delta: 0,
    rootId: 'ROOT-ATTACK-001',
    relation: 'supports',
    reversesSeqs: [],
    reasons: ['unverified_provenance', 'new_source_tight_trust', 'zero_committed_influence'],
    tags: ['schema-valid attack', 'zero influence'],
    engine: {
      prior: 0.48,
      rawBf: 100,
      boundedDelta: 0.04,
      rootSpent: 0,
      posterior: 0.52,
      integrity: 'L1 · PARSED',
    },
    metrics: metrics(241, 3, true, 702, 164, 84, 0),
    explanation: 'The structure parsed, but no external witness earned authority for its claims. It remains provisional with zero committed influence.',
  },
  {
    seq: 4,
    stepId: 'first-result-provisional',
    title: 'First result remains provisional',
    eventType: 'EVIDENCE_PROVISIONAL',
    verdict: 'PROVISIONAL',
    integrity: 'L1 · PARSED',
    delta: 0,
    rootId: 'ROOT-PILOT-001',
    relation: 'supports',
    reversesSeqs: [],
    reasons: ['first_result', 'replication_required', 'zero_committed_influence'],
    tags: ['pilot', 'provisional'],
    engine: {
      prior: 0.48,
      rawBf: 1.8,
      boundedDelta: 0.02,
      rootSpent: 0,
      posterior: 0.5,
      integrity: 'L1 · PARSED',
    },
    metrics: metrics(205, 3, true, 512, 116, 61, 104),
    explanation: 'The pilot is legible evidence, but its first-result status requires an independent replication witness before belief can move.',
  },
  {
    seq: 5,
    stepId: 'high-shock-escrow',
    title: 'High-shock derivative enters escrow',
    eventType: 'EVIDENCE_ESCROWED',
    verdict: 'ESCROW',
    integrity: 'L2 · VERIFIED',
    delta: 0,
    rootId: 'ROOT-ATTACK-001',
    relation: 'supports',
    reversesSeqs: [],
    reasons: ['high_shock:2.84', 'same_root_derivative', 'escrow_pending_review'],
    tags: ['high shock', 'escrow'],
    engine: {
      prior: 0.48,
      rawBf: 80,
      boundedDelta: 0.1,
      rootSpent: 0,
      posterior: 0.58,
      integrity: 'L2 · VERIFIED',
    },
    metrics: metrics(318, 3, true, 744, 172, 96, 0),
    explanation: 'Verification did not grant immediate influence. The proposed displacement exceeded the shock threshold, so the transaction was held in escrow.',
  },
  {
    seq: 6,
    stepId: 'independent-replication',
    title: 'Independent root replicates support',
    eventType: 'EVIDENCE_COMMITTED',
    verdict: 'COMMIT',
    integrity: 'L3 · REPLICATED',
    delta: 0.14,
    rootId: 'ROOT-REPLICATION-001',
    relation: 'replicates',
    reversesSeqs: [],
    reasons: ['independent_lineage', 'replication_confirmed', 'within_root_budget'],
    tags: ['replication', 'independent root'],
    engine: {
      prior: 0.48,
      rawBf: 3.5,
      boundedDelta: 0.14,
      rootSpent: 0.14,
      posterior: 0.62,
      integrity: 'L3 · REPLICATED',
    },
    metrics: metrics(149, 2, false, 638, 152, 46, 221),
    explanation: 'An independent experimental lineage corroborated the original result, earning L3 integrity and a larger evidence-weighted update.',
  },
  {
    seq: 7,
    stepId: 'same-root-duplicate',
    title: 'Derivative shares the original root budget',
    eventType: 'EVIDENCE_COMMITTED',
    verdict: 'COMMIT',
    integrity: 'L2 · VERIFIED',
    delta: 0.03,
    rootId: 'ROOT-SUPPORT-001',
    relation: 'supports',
    reversesSeqs: [],
    reasons: ['duplicate_lineage_detected', 'root_budget_clipped', 'bounded_to_remaining_budget'],
    tags: ['duplicate', 'root bounded'],
    engine: {
      prior: 0.62,
      rawBf: 4,
      boundedDelta: 0.03,
      rootSpent: 0.15,
      posterior: 0.65,
      integrity: 'L2 · VERIFIED',
    },
    metrics: metrics(173, 3, true, 602, 143, 55, 187),
    explanation: 'The newsletter descends from an already counted experiment. It could spend only the small remainder of that root’s shared budget.',
  },
  {
    seq: 8,
    stepId: 'unknown-claim-rejection',
    title: 'Unknown claim target is rejected',
    eventType: 'EVIDENCE_REJECTED',
    verdict: 'REJECT',
    integrity: 'L1 · PARSED',
    delta: 0,
    rootId: 'ROOT-UNKNOWN-001',
    relation: 'supports',
    reversesSeqs: [],
    reasons: ['unknown_claim:C404', 'graph_scope_violation', 'zero_committed_influence'],
    tags: ['unknown claim', 'rejected'],
    engine: null,
    metrics: metrics(98, 2, false, 476, 96, 29, 152),
    explanation: 'The target does not exist in the modeled claim graph. The reference monitor rejected the action before the engine could run.',
  },
  {
    seq: 9,
    stepId: 'final-root-retraction',
    title: 'Original support root is retracted',
    eventType: 'REVERSAL',
    verdict: 'REVERSAL',
    integrity: 'L2 · VERIFIED',
    delta: -0.15,
    rootId: 'ROOT-SUPPORT-001',
    relation: null,
    reversesSeqs: [1, 7],
    reasons: ['append_only_retraction', 'two_commits_reversed', 'root_budget_refunded'],
    tags: ['retraction', 'reversal'],
    engine: {
      prior: 0.65,
      rawBf: 0,
      boundedDelta: -0.15,
      rootSpent: 0,
      posterior: 0.5,
      integrity: 'L2 · VERIFIED',
    },
    metrics: metrics(18, 0, false, 0, 0, 0, 0),
    explanation: 'The append-only reversal exactly negated every committed delta descending from the retracted original root. Independent evidence remains intact.',
  },
]
